name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up environment (if needed)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl pandoc jq

      # Execute the build script
      - name: Run gen script
        run: ./gen
