name: shfmt

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install shfmt
        run: |
          sudo curl -sSL -o /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_linux_amd64
          sudo chmod +x /usr/local/bin/shfmt

      - name: Run shfmt
        run: shfmt -p -i 4 -ci -bn -sr -d gen
